version: '3.4'

services:
  front:
    image: umino0124/bao:front-end
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
